### ISSUE TITLE
_process_line方法中未对首字母“>”进行处理

### ISSUE THREAD

**Issue by ncjoe** [KHwang9883/MobileModels-csv#3]
```
process: samsung_global_en.md
exception process samsung: unknown line: > This page is incomplete. You can check [Google Play Supported Devices](http://storage.googleapis.com/play_public/supported_devices.html) for a full list of Samsung mobile devices.
Traceback (most recent call last):
  File "/Users/wuailun/Work/Git/MobileModels-csv/gen_csv.py", line 302, in sync_brands
    _process_line(line)
  File "/Users/wuailun/Work/Git/MobileModels-csv/gen_csv.py", line 272, in _process_line
    raise ValueError(f'unknown line: {line}')
ValueError: unknown line: > This page is incomplete. You can check [Google Play Supported Devices](http://storage.googleapis.com/play_public/supported_devices.html) for a full list of Samsung mobile devices.
```
samsung_global_en.md 文档中首字符“>”在代码中未处理，脚本报错。

**Comment by KHwang9883** [comment]
不影响正常生成，可以忽略
